name: stat-rethink2
channels:
- defaults
dependencies:
  - git
  - jupyter
  - seaborn
  - mkl-service
  - pip
  - pip:
     - watermark
     - arviz
     - pymc3
     - causalgraphicalmodels
     - daft
     - statsmodels
     - pymc3-quap
