name: stat-rethink2
channels:
  - conda-forge
  - defaults
dependencies:
  - libpython
  - blas
  - git
  - jupyter
  - seaborn
  - mkl-service
  - m2w64-toolchain
  - python-graphviz
  - scipy
  - numba
  - pip
  - pip:
     - watermark
     - arviz
     - pymc3
     - causalgraphicalmodels
     - daft
     - statsmodels
     - pymc3-quap


